---
- hosts: all
  gather_facts: yes
  vars_files:
    - [ "vars/{{ ansible_os_family }}.yml", "vars/os-defaults.yml" ]
  roles:
    - { role: users, tags: users }
    - { role: sshpassauth, tags: sshpassauth }
